# Generated by Django 2.0.9 on 2018-11-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('pub_date', models.DateField(blank=True)),
                ('instagram_id', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='instagram')),
                ('image_crop', models.ImageField(blank=True, upload_to='instagram/final')),
                ('text', models.TextField(blank=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('type', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
